[workspace]
members = ["app", "bootstrap", "shared"]
resolver = "2"

[workspace.package]
license = "MIT"
license-file = "LICENSE"
authors = ["Pascal Behmenburg"]


[profile.dev.package.backtrace]
opt-level = 3

[profile.dev.package.askama_derive]
opt-level = 3
